using Autodesk.Revit.ApplicationServices;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using System.Linq;
using Autodesk.Revit.UI.Selection;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Autodesk.Revit.DB.Events;
using System.Reflection;
using System.IO;
using System.Runtime;
using Autodesk.Revit.DB.Architecture;
using Microsoft.SqlServer.Server;
using System.Xml.Linq;
using System.Diagnostics.Eventing.Reader;
using Application = Autodesk.Revit.ApplicationServices.Application;

namespace Revit.Common
{
    [Transaction(TransactionMode.Manual)]
    public class DimensionFloorsEC : IExternalCommand
    {
        public Result Execute(
          ExternalCommandData commandData,
          ref string message,
          ElementSet elements)
        {
            UIApplication uiapp = commandData.Application;
            UIDocument uidoc = uiapp.ActiveUIDocument;
            Application app = uiapp.Application;
            Document doc = uidoc.Document;
            Autodesk.Revit.DB.View initialView = uidoc.ActiveView;

            bool OK = true;
            string errors = "";
            if (!Utils.VerifyIfProjectParameterExists(doc, "Ambiente"))
            {
                errors += "\n- Ambiente";
                OK = false;
            }
            if (!Utils.VerifyIfProjectParameterExists(doc, "Reforço de Tela"))
            {
                errors += "\n- Reforço de Tela";
                OK = false;
            }
            if (!OK)
            {
                Autodesk.Revit.UI.TaskDialog.Show("ATENÇÃO!", $"Não foi possível executar o comando por não existir no modelo os seguintes parâmetros:\n {errors}");
                return Result.Cancelled;
            }

            if (uidoc.ActiveView is View3D)
            {
                Autodesk.Revit.UI.TaskDialog.Show("Atenção!", "Abra uma vista de planta para rodar o plug-in!");
                return Result.Cancelled;
            }

            DimensionType cotaLPEType = new FilteredElementCollector(doc)
                   .OfClass(typeof(DimensionType))
                   .Where(a => a.Name == "Cota_LPE")
                   .Cast<DimensionType>()
                   .FirstOrDefault();

            if (cotaLPEType == null)
            {
                Autodesk.Revit.UI.TaskDialog.Show("ATENÇÃO!", $"Não foi possível executar o comando por não existir as seguintes famílias no modelo:\n Cota_LPE");
                return Result.Cancelled;
            }

            ExternalApplication.LPEApp.uiApp = uiapp;
            ExternalApplication.LPEApp.ShowDimensionFloorsUI();

            return Result.Succeeded;
        }
    }
}
